### ISSUE TITLE
Error when trying to initialize with Acquia recipe

### ISSUE THREAD

**Issue by DicksB** [lando/acquia#9]
MacOS 11.3.1
Docker Desktop 3.3.3
Lando 3.1.4

Having corrected my ACLI problem (thanks to Mike Milano), I got my "hello" application up and running under 3.1.4. I then tried initializing a project with the Acquia Cloud recipe:

% lando init --source acquia -v
? Enter an Acquia API key (obfuscated)
? Enter an Acquia API secret [hidden]
lando 09:41:24 ERROR ==> TypeError: Cannot read property 'data' of undefined
    at /snapshot/lando/build/cli/integrations/lando-acquia/lib/api.js
    at processTicksAndRejections (internal/process/task_queues.js:97:5) 

Same error occurs whether initializing an empty directory, or a directory into which I've already cloned a codebase from Acquia Cloud:

% lando init -v --source cwd --recipe acquia
? Enter an Acquia API key (obfuscated)
? Enter an Acquia API secret [hidden]
lando 09:40:00 ERROR ==> TypeError: Cannot read property 'data' of undefined
    at /snapshot/lando/build/cli/integrations/lando-acquia/lib/api.js
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

**Comment by michaelsilao** [comment]
hi just wanted to know if someone has resolved this? im getting this same issue currently on my office machine

**Comment by sammykumar** [comment]
I had the same issue. My environment MacOS (M1) is behind a corporate VPN (Zscaler). Adding my Zscaler's root certificate to Node and Curl solved my issue.

Node: https://docs.devwithlando.io/guides/lando-corporate-network-tips.html#add-cert-to-host-environment
Curl: https://docs.devwithlando.io/guides/lando-corporate-network-tips.html#adding-certs-for-native-curl

**Comment by AaronFeledy** [comment]
Lando has since improved network and certificate handling and the Acquia plugin now has improved authentication handling. This is likely no longer an issue, but feel free to reopen if it still comes up.
